/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as ZoneZoneIdRouteImport } from './routes/zone.$zoneId'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as OperatorProfileRouteImport } from './routes/operator.profile'
import { Route as OperatorLoginRouteImport } from './routes/operator.login'
import { Route as OperatorAllotRouteImport } from './routes/operator.allot'
import { Route as OperatorActivityRouteImport } from './routes/operator.activity'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const ZoneZoneIdRoute = ZoneZoneIdRouteImport.update({
  id: '/zone/$zoneId',
  path: '/zone/$zoneId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorProfileRoute = OperatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorLoginRoute = OperatorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAllotRoute = OperatorAllotRouteImport.update({
  id: '/allot',
  path: '/allot',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorActivityRoute = OperatorActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => OperatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/feedback': typeof FeedbackRoute
  '/notifications': typeof NotificationsRoute
  '/operator': typeof OperatorRouteWithChildren
  '/profile': typeof ProfileRoute
  '/zones': typeof ZonesRoute
  '/operator/activity': typeof OperatorActivityRoute
  '/operator/allot': typeof OperatorAllotRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/operator/': typeof OperatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/feedback': typeof FeedbackRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/zones': typeof ZonesRoute
  '/operator/activity': typeof OperatorActivityRoute
  '/operator/allot': typeof OperatorAllotRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/operator': typeof OperatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/feedback': typeof FeedbackRoute
  '/notifications': typeof NotificationsRoute
  '/operator': typeof OperatorRouteWithChildren
  '/profile': typeof ProfileRoute
  '/zones': typeof ZonesRoute
  '/operator/activity': typeof OperatorActivityRoute
  '/operator/allot': typeof OperatorAllotRoute
  '/operator/login': typeof OperatorLoginRoute
  '/operator/profile': typeof OperatorProfileRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/zone/$zoneId': typeof ZoneZoneIdRoute
  '/operator/': typeof OperatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/feedback'
    | '/notifications'
    | '/operator'
    | '/profile'
    | '/zones'
    | '/operator/activity'
    | '/operator/allot'
    | '/operator/login'
    | '/operator/profile'
    | '/pay/$bookingId'
    | '/ticket/$ticketId'
    | '/zone/$zoneId'
    | '/operator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/feedback'
    | '/notifications'
    | '/profile'
    | '/zones'
    | '/operator/activity'
    | '/operator/allot'
    | '/operator/login'
    | '/operator/profile'
    | '/pay/$bookingId'
    | '/ticket/$ticketId'
    | '/zone/$zoneId'
    | '/operator'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/feedback'
    | '/notifications'
    | '/operator'
    | '/profile'
    | '/zones'
    | '/operator/activity'
    | '/operator/allot'
    | '/operator/login'
    | '/operator/profile'
    | '/pay/$bookingId'
    | '/ticket/$ticketId'
    | '/zone/$zoneId'
    | '/operator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  FeedbackRoute: typeof FeedbackRoute
  NotificationsRoute: typeof NotificationsRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ZonesRoute: typeof ZonesRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  ZoneZoneIdRoute: typeof ZoneZoneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/zone/$zoneId': {
      id: '/zone/$zoneId'
      path: '/zone/$zoneId'
      fullPath: '/zone/$zoneId'
      preLoaderRoute: typeof ZoneZoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/profile': {
      id: '/operator/profile'
      path: '/profile'
      fullPath: '/operator/profile'
      preLoaderRoute: typeof OperatorProfileRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/login': {
      id: '/operator/login'
      path: '/login'
      fullPath: '/operator/login'
      preLoaderRoute: typeof OperatorLoginRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/allot': {
      id: '/operator/allot'
      path: '/allot'
      fullPath: '/operator/allot'
      preLoaderRoute: typeof OperatorAllotRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/activity': {
      id: '/operator/activity'
      path: '/activity'
      fullPath: '/operator/activity'
      preLoaderRoute: typeof OperatorActivityRouteImport
      parentRoute: typeof OperatorRoute
    }
  }
}

interface OperatorRouteChildren {
  OperatorActivityRoute: typeof OperatorActivityRoute
  OperatorAllotRoute: typeof OperatorAllotRoute
  OperatorLoginRoute: typeof OperatorLoginRoute
  OperatorProfileRoute: typeof OperatorProfileRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorActivityRoute: OperatorActivityRoute,
  OperatorAllotRoute: OperatorAllotRoute,
  OperatorLoginRoute: OperatorLoginRoute,
  OperatorProfileRoute: OperatorProfileRoute,
  OperatorIndexRoute: OperatorIndexRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  FeedbackRoute: FeedbackRoute,
  NotificationsRoute: NotificationsRoute,
  OperatorRoute: OperatorRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ZonesRoute: ZonesRoute,
  PayBookingIdRoute: PayBookingIdRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  ZoneZoneIdRoute: ZoneZoneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
